
#https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
 
LineLength:
  Description: 'Limit lines to 79 characters.'
  Enabled: false
DefWithParentheses:
  Description: 'Use def with parentheses when there are arguments.'
  Enabled: false
